import argparse

from constants import DEFAULT_MODEL_DIR, DEFAULT_MODEL_NAME


def parse_args():
    parser = argparse.ArgumentParser(description="demo4: parallel HTML generation and QtWebEngine rendering")
    parser.add_argument("--cols", type=int, default=6)
    parser.add_argument("--rows", type=int, default=4)
    parser.add_argument("--groups", type=int, default=5)
    parser.add_argument("--page-scale", type=float, default=0.30)
    parser.add_argument("--render-hz", type=int, default=20)
    parser.add_argument("--max-page-loads-per-tick", type=int, default=2)
    parser.add_argument("--max-text-page-loads-per-tick", type=int, default=24)
    parser.add_argument("--html-min-delta", type=int, default=2048)
    parser.add_argument("--html-max-stale-ms", type=int, default=2000)
    parser.add_argument("--html-stagger-ms", type=int, default=1000)
    parser.add_argument("--html-refresh-interval-ms", type=int, default=650)
    parser.add_argument("--preview-refresh-interval-ms", type=int, default=120)
    parser.add_argument("--producer-flush-hz", type=int, default=10)
    parser.add_argument("--queue-size", type=int, default=2)
    parser.add_argument("--ui-poll-ms", type=int, default=20)
    parser.add_argument("--max-gui-messages", type=int, default=128)
    parser.add_argument("--group-render-delay-ms", type=int, default=0)
    parser.add_argument("--auto-switch-group-seconds", type=float, default=0.0, help="auto switch to the next group every N seconds; 0 disables it, positive values are clamped to at least 3 seconds")
    parser.add_argument("--auto-bounce-scroll", dest="auto_bounce_scroll", action="store_true", help="automatically scroll rendered HTML pages down and back up in a loop")
    parser.add_argument("--no-auto-bounce-scroll", dest="auto_bounce_scroll", action="store_false", help="disable automatic down-and-up bounce scrolling for rendered HTML pages")
    parser.set_defaults(auto_bounce_scroll=True)
    parser.add_argument("--auto-bounce-scroll-step", type=int, default=24, help="pixels to move each auto bounce scroll tick")
    parser.add_argument("--auto-bounce-scroll-tick-ms", type=int, default=16, help="interval in milliseconds between auto bounce scroll ticks")
    parser.add_argument("--auto-bounce-scroll-edge-pause-ms", type=int, default=500, help="pause duration in milliseconds when auto bounce scroll reaches top or bottom")
    parser.add_argument("--allow-scripts", action="store_true")
    parser.add_argument("--enable-webengine-gpu", dest="disable_webengine_gpu", action="store_false")
    parser.set_defaults(disable_webengine_gpu=True)
    parser.add_argument("--prompt", default=None)
    parser.add_argument("--prompt-file", default=None)
    parser.add_argument("--jsonl-log", default="demo4_outputs.jsonl", help='write one JSONL line per page, format: {"text":"..."}')
    parser.add_argument("--no-jsonl-log", dest="jsonl_log", action="store_const", const=None)
    parser.add_argument("--model-dir", default=DEFAULT_MODEL_DIR)
    parser.add_argument("--model-name", default=DEFAULT_MODEL_NAME)
    parser.add_argument("--generation-length", type=int, default=0, help="max tokens per page; 0 means run until all pages complete HTML")
    parser.add_argument("--sampler-top-p", type=float, default=0.6)
    parser.add_argument("--sampler-temp", type=float, default=1.0)
    parser.add_argument("--sampler-top-k", type=int, default=64)
    parser.add_argument("--presence-penalty", type=float, default=1.0)
    parser.add_argument("--perf-interval", type=int, default=30)
    parser.add_argument("--perf-sync-interval", type=int, default=30)
    parser.add_argument("--gui-nice", type=int, default=5)
    parser.add_argument("--model-nice", type=int, default=0)
    parser.add_argument("--window-w", type=int, default=1600)
    parser.add_argument("--window-h", type=int, default=1000)
    return parser.parse_args()
